//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace takimdeneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class futbolcular
    {
        public futbolcular()
        {
            this.transfer = new HashSet<transfer>();
        }
    
        public string İsim { get; set; }
        public string Mevki { get; set; }
        public Nullable<double> TZ_Gol { get; set; }
        public Nullable<double> TZ_Lig_Maç { get; set; }
        public string Kullandığı_Ayak { get; set; }
        public double OID { get; set; }
        public Nullable<double> Klup_id { get; set; }
        public string Ülke { get; set; }
        public string Boy { get; set; }
        public string Ağırlık { get; set; }
        public Nullable<double> Yaş { get; set; }
        public string Piyasa_Değeri { get; set; }
    
        public virtual takim takim { get; set; }
        public virtual ICollection<transfer> transfer { get; set; }
    }
}
