//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace takimdeneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfer
    {
        public string İsim { get; set; }
        public Nullable<double> o_id { get; set; }
        public Nullable<double> Yeni_takim_id { get; set; }
        public Nullable<double> Eski_takim_id { get; set; }
        public string Tür { get; set; }
        public string Bedel { get; set; }
        public int transfer_id { get; set; }
    
        public virtual futbolcular futbolcular { get; set; }
        public virtual takim takim { get; set; }
        public virtual takim takim1 { get; set; }
    }
}
