//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace takimdeneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class uye
    {
        public string ad { get; set; }
        public string e_mail { get; set; }
        public string sifre { get; set; }
        public int id { get; set; }
    }
}
